**Sanity check**: $P_\sigma e_i = e_{\sigma(i)}$

In [2]:
import numpy as np
# Define the permutation sigma in 0-based indexing
# sigma = (1 2 3) -> [1, 2, 0, 3]
sigma = [1, 2, 0, 3]

# Size of the permutation
p = len(sigma)

# Construct the permutation matrix P_sigma
P_sigma = np.zeros((p, p), dtype=int)
for j in range(p):
    i = sigma[j]
    P_sigma[i, j] = 1

print("Permutation matrix P_sigma:")
print(P_sigma)

# Verify that P_sigma * e_j = e_sigma(j)
for j in range(p):
    e_j = np.zeros(p)
    e_j[j] = 1
    result = P_sigma @ e_j
    e_sigma_j = np.zeros(p)
    e_sigma_j[sigma[j]] = 1

    print(f"\ne_{j + 1} = {e_j}")
    print(f"P_sigma * e_{j + 1} = {result}")
    print(f"e_sigma({j + 1}) = {e_sigma_j}")
    print(f"Equal? {np.allclose(result, e_sigma_j)}")


Permutation matrix P_sigma:
[[0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]

e_1 = [1. 0. 0. 0.]
P_sigma * e_1 = [0. 1. 0. 0.]
e_sigma(1) = [0. 1. 0. 0.]
Equal? True

e_2 = [0. 1. 0. 0.]
P_sigma * e_2 = [0. 0. 1. 0.]
e_sigma(2) = [0. 0. 1. 0.]
Equal? True

e_3 = [0. 0. 1. 0.]
P_sigma * e_3 = [1. 0. 0. 0.]
e_sigma(3) = [1. 0. 0. 0.]
Equal? True

e_4 = [0. 0. 0. 1.]
P_sigma * e_4 = [0. 0. 0. 1.]
e_sigma(4) = [0. 0. 0. 1.]
Equal? True
